[build-system]
requires = ["maturin>=1.12,<2.0"]
build-backend = "maturin"

[project]
name = "dbsampler"
version = "0.4.0"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
authors = [
  { name="António Leitão", email="aleitao@novaims.unl.pt" },
]
description = "Decision Boundary Sampler"
readme = "README.md"

[project.urls]
homepage = "https://github.com/antonio-leitao/dbsampler"
repository = "https://github.com/antonio-leitao/dbsampler"

[tool.maturin]
features = ["pyo3/extension-module"]

[dependency-groups]
dev = [
    "matplotlib>=3.10.8",
    "numpy>=2.2.6",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
]

